-- 캐릭터 데이터
INSERT IGNORE INTO card_info
(card_info_id,
 name,
 english_name,
 image_url)
VALUES (1,
        '공작',
        'Duke',
        'duke.jpg'),
       (2,
        '사령관',
        'Captain',
        'captain.jpg'),
       (3,
        '암살자',
        'Assassin',
        'assassin.jpg'),
       (4,
        '귀부인',
        'Contessa',
        'contessa.jpg'),
       (5,
        '외교관',
        'Ambassador',
        'ambassador.jpg');

-- 행동 데이터
INSERT IGNORE INTO action
(action_id,
 name,
 english_name,
 description,
 specific_character,
 counteraction_character1,
 counteraction_character2,
 can_be_blocked,
 can_be_challenged)
VALUES (1,
        '수입',
        'Income',
        '1원 획득. 방해할 수 없습니다.',
        0,
        0,
        0,
        false,
        false),
       (2,
        '해외원조',
        'Foreign Aid',
        '2원 획득. 공작으로 방해할 수 있습니다.',
        0,
        1,
        0,
        true,
        true),
       (3,
        '징세',
        'Tax',
        '3원 획득. 방해할 수 없습니다.',
        1,
        0,
        0,
        false,
        true),
       (4,
        '강탈',
        'Steal',
        '다른 플레이어로부터 2원을 빼앗아옵니다. 사령관/외교관으로 방해할 수 있습니다.',
        2,
        2,
        5,
        true,
        true),
       (5,
        '암살',
        'Assassinate',
        '3원 지불. 영향력을 잃게 할 플레이어를 고르세요. 귀부인으로 방해할 수 있습니다.',
        3,
        4,
        0,
        true,
        true),
       (6,
        '교환',
        'Exchange',
        '7원 지불. 영향력을 잃게 할 플레이어를 고르세요. 방해할 수 없습니다.',
        5,
        0,
        0,
        false,
        true),
       (7,
        '쿠',
        'Coup',
        '7원 지불. 영향력을 잃게 할 플레이어를 고르세요. 방해할 수 없습니다.',
        0,
        0,
        0,
        false,
        false)